[283.836603165] 2018-10-22 16:52:42,617 - INFO - launcher: Starting sanity checks
[286.834955215] 2018-10-22 16:52:42,620 - INFO - launcher: Checking for Python 3.5+
[287.834405899] 2018-10-22 16:52:42,621 - INFO - launcher: Checking console encoding
[289.833307266] 2018-10-22 16:52:42,623 - INFO - launcher: Setting console encoding to UTF-8
[289.833307266] 2018-10-22 16:52:42,623 - INFO - launcher: Ensuring we're in the right environment
[292.831897736] 2018-10-22 16:52:42,626 - INFO - launcher: Adding local bins/ folder to path
[5113.840579987] 2018-10-22 16:52:47,447 - INFO - launcher: Required checks passed.
[5114.840507507] 2018-10-22 16:52:47,448 - INFO - launcher: Optional checks passed.
[5114.840507507] 2018-10-22 16:52:47,448 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[17.0227935314178467] 2018-10-22 16:52:59,356 - WARNING - musicbot.config | In config.py::MainThread(4448), line 113 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[17.0237927436828613] 2018-10-22 16:52:59,357 - INFO - musicbot.config | In config.py::MainThread(4448), line 124 in run_checks: Using i18n: config/i18n/en.json
[17.0532488822937012] 2018-10-22 16:52:59,386 - DEBUG - musicbot.json | In json.py::MainThread(4448), line 8 in __init__: Init JSON obj with config/i18n/en.json
[17.1848094463348389] 2018-10-22 16:52:59,518 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 223 in _setup_logging: Set logging level to INFO
[17.1848094463348389] 2018-10-22 16:52:59,518 - INFO - musicbot.bot | In bot.py::MainThread(4448), line 83 in __init__: Starting MusicBot 1.9.8_1
[17.1858088970184326] 2018-10-22 16:52:59,519 - INFO - musicbot.bot | In bot.py::MainThread(4448), line 89 in __init__: Loaded autoplaylist with 2531 entries
[20.4628374576568604] 2018-10-22 16:53:02,796 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 913 in on_ready: Connection established, ready to go.
[20.4638359546661377] 2018-10-22 16:53:02,797 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 334 in _cache_app_info: Caching app info
[20.6508307456970215] 2018-10-22 16:53:02,984 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 735 in _scheck_ensure_env: Ensuring data folders exist
[20.6748163700103760] 2018-10-22 16:53:03,008 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 751 in _scheck_server_permissions: Checking server permissions
[20.6758155822753906] 2018-10-22 16:53:03,009 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 755 in _scheck_autoplaylist: Auditing autoplaylist
[20.6758155822753906] 2018-10-22 16:53:03,009 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 759 in _scheck_configs: Validating config
[20.6758155822753906] 2018-10-22 16:53:03,009 - DEBUG - musicbot.config | In config.py::MainThread(4448), line 213 in async_validate: Validating options...
[20.6768147945404053] 2018-10-22 16:53:03,010 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 762 in _scheck_configs: Validating permissions config
[20.6768147945404053] 2018-10-22 16:53:03,010 - DEBUG - musicbot.permissions | In permissions.py::MainThread(4448), line 65 in async_validate: Validating permissions...
[20.6768147945404053] 2018-10-22 16:53:03,010 - INFO - musicbot.bot | In bot.py::MainThread(4448), line 930 in on_ready: Connected: 503916003336650766/HuboxxIMG#5293
[20.6818132400512695] 2018-10-22 16:53:03,015 - INFO - musicbot.bot | In bot.py::MainThread(4448), line 938 in on_ready: Owner:     310867995926986753/huboxx#4466

[20.6858096122741699] 2018-10-22 16:53:03,019 - INFO - musicbot.bot | In bot.py::MainThread(4448), line 941 in on_ready: Guild List:
[20.6868088245391846] 2018-10-22 16:53:03,020 - INFO - musicbot.bot | In bot.py::MainThread(4448), line 944 in on_ready:  - LeagueOfLegends/GRACZE
[20.6888086795806885] 2018-10-22 16:53:03,022 - INFO - musicbot.bot | In bot.py::MainThread(4448), line 944 in on_ready:  - Aion 8B
[20.6928071975708008] 2018-10-22 16:53:03,026 - INFO - musicbot.bot | In bot.py::MainThread(4448), line 990 in on_ready: Not bound to any text channels
[20.6938054561614990] 2018-10-22 16:53:03,027 - INFO - musicbot.bot | In bot.py::MainThread(4448), line 1016 in on_ready: Not autojoining any voice channels
[20.6958041191101074] 2018-10-22 16:53:03,029 - INFO - musicbot.bot | In bot.py::MainThread(4448), line 261 in _join_startup_channels: Found resumable voice channel LeagueOfLegends/GRACZE/MAX5 ●
[20.6978027820587158] 2018-10-22 16:53:03,031 - INFO - musicbot.bot | In bot.py::MainThread(4448), line 276 in _join_startup_channels: Attempting to join LeagueOfLegends/GRACZE/MAX5 ●
[21.3891124725341797] 2018-10-22 16:53:03,722 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 695 in deserialize_queue: Deserializing queue for 489057043496304640
[21.7772140502929688] 2018-10-22 16:53:04,110 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 417 in get_player: Created player via deserialization for guild 489057043496304640 with 1 entries
[21.7772140502929688] 2018-10-22 16:53:04,110 - INFO - musicbot.bot | In bot.py::MainThread(4448), line 292 in _join_startup_channels: Joined LeagueOfLegends/GRACZE/MAX5 ●
[21.7792134284973145] 2018-10-22 16:53:04,112 - DEBUG - musicbot.entry | In entry.py::MainThread(4448), line 56 in get_ready_future: Created future for audio_cache\youtube-60ItHLz5WEA-Alan_Walker_-_Faded.webm
[21.7792134284973145] 2018-10-22 16:53:04,112 - FFMPEG - musicbot.player | In player.py::MainThread(4448), line 276 in _play: Creating player with options: -nostdin -vn audio_cache\youtube-60ItHLz5WEA-Alan_Walker_-_Faded.webm
[21.7862102985382080] 2018-10-22 16:53:04,119 - DEBUG - musicbot.player | In player.py::MainThread(4448), line 287 in _play: Playing <discord.player.PCMVolumeTransformer object at 0x05876F30> using <discord.voice_client.VoiceClient object at 0x0581E2F0>
[21.7942051887512207] 2018-10-22 16:53:04,127 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 452 in on_player_play: Running on_player_play
[21.7952051162719727] 2018-10-22 16:53:04,128 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 671 in serialize_queue: Serializing queue for 489057043496304640
[27.8807630538940430] 2018-10-22 16:53:10,214 - INFO - musicbot.bot | In bot.py::MainThread(4448), line 2598 in on_message: 310867995926986753/huboxx#4466: $skip
[28.0476932525634766] 2018-10-22 16:53:10,381 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 509 in on_player_finished_playing: Running on_player_finished_playing
[28.0476932525634766] 2018-10-22 16:53:10,381 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 671 in serialize_queue: Serializing queue for 489057043496304640
[28.0566856861114502] 2018-10-22 16:53:10,390 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 505 in on_player_stop: Running on_player_stop
[28.0576848983764648] 2018-10-22 16:53:10,391 - WARNING - musicbot.bot | In bot.py::MainThread(4448), line 788 in safe_send_message: Cannot send message to "●muzyczny●", no permission
[32.6687777042388916] 2018-10-22 16:53:15,002 - INFO - musicbot.bot | In bot.py::MainThread(4448), line 2598 in on_message: 310867995926986753/huboxx#4466: $help
[33.0468053817749023] 2018-10-22 16:53:15,380 - WARNING - musicbot.bot | In bot.py::MainThread(4448), line 788 in safe_send_message: Cannot send message to "●muzyczny●", no permission
[64.9952831268310547] 2018-10-22 16:53:47,328 - INFO - musicbot.bot | In bot.py::MainThread(4448), line 2598 in on_message: 455117792010567710/f3rnv2#1978: $play rise
[66.6929392814636230] 2018-10-22 16:53:49,026 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 1351 in cmd_play: {'_type': 'url', 'url': 'ytsearch:rise', 'ie_key': None, 'extractor': 'generic', 'webpage_url': 'rise', 'webpage_url_basename': 'rise', 'extractor_key': 'Generic'}
[71.2965333461761475] 2018-10-22 16:53:53,630 - DEBUG - musicbot.entry | In entry.py::MainThread(4448), line 56 in get_ready_future: Created future for None
[71.2995326519012451] 2018-10-22 16:53:53,633 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 586 in on_player_entry_added: Running on_player_entry_added
[71.3005311489105225] 2018-10-22 16:53:53,634 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 671 in serialize_queue: Serializing queue for 489057043496304640
[71.3225209712982178] 2018-10-22 16:53:53,656 - INFO - musicbot.entry | In entry.py::MainThread(4448), line 285 in _really_download: Download started: https://www.youtube.com/watch?v=fB8TyLTD7EE
[71.5027184486389160] 2018-10-22 16:53:53,836 - WARNING - musicbot.bot | In bot.py::MainThread(4448), line 788 in safe_send_message: Cannot send message to "●muzyczny●", no permission
[73.2926199436187744] 2018-10-22 16:53:55,626 - DEBUG - musicbot.entry | In entry.py::MainThread(4448), line 56 in get_ready_future: Created future for None
[73.3395977020263672] 2018-10-22 16:53:55,673 - INFO - musicbot.entry | In entry.py::MainThread(4448), line 295 in _really_download: Download complete: https://www.youtube.com/watch?v=fB8TyLTD7EE
[73.3495929241180420] 2018-10-22 16:53:55,683 - FFMPEG - musicbot.player | In player.py::MainThread(4448), line 276 in _play: Creating player with options: -nostdin -vn audio_cache\youtube-fB8TyLTD7EE-RISE_ft._The_Glitch_Mob_Mako_and_The_Word_Alive_Worlds_2018_-_League_of_Legends.webm
[73.3565876483917236] 2018-10-22 16:53:55,690 - DEBUG - musicbot.player | In player.py::MainThread(4448), line 287 in _play: Playing <discord.player.PCMVolumeTransformer object at 0x04A18DF0> using <discord.voice_client.VoiceClient object at 0x0581E2F0>
[73.4535317420959473] 2018-10-22 16:53:55,787 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 452 in on_player_play: Running on_player_play
[73.4535317420959473] 2018-10-22 16:53:55,787 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 671 in serialize_queue: Serializing queue for 489057043496304640
[126.3210840225219727] 2018-10-22 16:54:48,654 - ERROR - musicbot.bot | In bot.py::MainThread(4448), line 901 in on_error: Exception in on_voice_state_update
Traceback (most recent call last):
  File "C:\Users\Gocha i Tadzio\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\48721\Documents\MusicBot\musicbot\bot.py", line 2796, in on_voice_state_update
    player = await self.get_player(channel)
  File "C:\Users\48721\Documents\MusicBot\musicbot\bot.py", line 425, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use $summon to summon it to your voice channel.
[283.9399785995483398] 2018-10-22 16:57:26,273 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 509 in on_player_finished_playing: Running on_player_finished_playing
[283.9399785995483398] 2018-10-22 16:57:26,273 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 671 in serialize_queue: Serializing queue for 489057043496304640
[283.9439814090728760] 2018-10-22 16:57:26,277 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 505 in on_player_stop: Running on_player_stop
[539.8090398311614990] 2018-10-22 17:01:42,142 - INFO - musicbot.bot | In bot.py::MainThread(4448), line 2598 in on_message: 310867995926986753/huboxx#4466: $play PUT-IN - Piosenka o Białym Misiu
[540.0910522937774658] 2018-10-22 17:01:42,424 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 1351 in cmd_play: {'_type': 'url', 'url': 'ytsearch:PUT-IN - Piosenka o Białym Misiu', 'ie_key': None, 'extractor': 'generic', 'webpage_url': 'PUT-IN - Piosenka o Białym Misiu', 'webpage_url_basename': 'PUT-IN - Piosenka o Białym Misiu', 'extractor_key': 'Generic'}
[544.7728242874145508] 2018-10-22 17:01:47,106 - DEBUG - musicbot.entry | In entry.py::MainThread(4448), line 56 in get_ready_future: Created future for None
[544.7768242359161377] 2018-10-22 17:01:47,110 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 586 in on_player_entry_added: Running on_player_entry_added
[544.7778227329254150] 2018-10-22 17:01:47,111 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 671 in serialize_queue: Serializing queue for 489057043496304640
[544.9226639270782471] 2018-10-22 17:01:47,256 - INFO - musicbot.entry | In entry.py::MainThread(4448), line 285 in _really_download: Download started: https://www.youtube.com/watch?v=e_ooxjzzR0o
[545.0953805446624756] 2018-10-22 17:01:47,428 - WARNING - musicbot.bot | In bot.py::MainThread(4448), line 788 in safe_send_message: Cannot send message to "●muzyczny●", no permission
[546.7697222232818604] 2018-10-22 17:01:49,103 - DEBUG - musicbot.entry | In entry.py::MainThread(4448), line 56 in get_ready_future: Created future for None
[547.0946612358093262] 2018-10-22 17:01:49,428 - INFO - musicbot.entry | In entry.py::MainThread(4448), line 295 in _really_download: Download complete: https://www.youtube.com/watch?v=e_ooxjzzR0o
[547.1046552658081055] 2018-10-22 17:01:49,438 - FFMPEG - musicbot.player | In player.py::MainThread(4448), line 276 in _play: Creating player with options: -nostdin -vn audio_cache\youtube-e_ooxjzzR0o-PUT-IN_-_Piosenka_o_Bia_ym_Misiu_Oficjalny_Teledysk.webm
[547.1126523017883301] 2018-10-22 17:01:49,446 - DEBUG - musicbot.player | In player.py::MainThread(4448), line 287 in _play: Playing <discord.player.PCMVolumeTransformer object at 0x06618E70> using <discord.voice_client.VoiceClient object at 0x0581E2F0>
[547.1166491508483887] 2018-10-22 17:01:49,450 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 452 in on_player_play: Running on_player_play
[547.1166491508483887] 2018-10-22 17:01:49,450 - DEBUG - musicbot.bot | In bot.py::MainThread(4448), line 671 in serialize_queue: Serializing queue for 489057043496304640
